### ISSUE TITLE
App crashes when running tests

### ISSUE THREAD

**Issue by lmj0011** [nuxt/adonuxt#17]
After running API tests with Japa, I get the following error.

```sh
landan@lj-desktop:~/www/adonuxt_test$ npm run dev

> adonuxt_test@1.0.0 dev /home/landan/www/adonuxt_test
> npm run watch && node ./ace nuxtbuild && NODE_ENV=development node server.js 


> adonuxt_test@1.0.0 watch /home/landan/www/adonuxt_test
> nodemon --watch app --watch bootstrap --watch config --watch .env

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/landan/www/adonuxt_test/app/**/* /home/landan/www/adonuxt_test/bootstrap/**/* /home/landan/www/adonuxt_test/config/**/* .env
[nodemon] starting `node server.js`
info adonis:framework +0ms serving app on localhost:4000
webpack built a325d6a2a80074ee8732 in 3918ms
webpack building...
./.nuxt/server.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/landan/www/adonuxt_test/.nuxt/server.js'
    at Error (native)
webpack built 38ed4d989d21060ca708 in 984ms
Hash: 38ed4d989d21060ca708
Version: webpack 2.2.0
Time: 984ms
               Asset     Size  Chunks  Chunk Names
      nuxt.bundle.js  81.3 kB       0  app
    vendor.bundle.js   295 kB       1  vendor
  nuxt.bundle.js.map  90.7 kB       0  app
vendor.bundle.js.map   362 kB       1  vendor

ERROR in ./.nuxt/client.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/landan/www/adonuxt_test/.nuxt/client.js'
    at Error (native)
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
webpack built a325d6a2a80074ee8732 in 863ms
webpack built 74d66fc7320d80a25c40 in 4385ms
```

if I run the tests again the app crashes

```sh
webpack built 74d66fc7320d80a25c40 in 5092ms
Entry module not found: Error: Can't resolve '/home/landan/www/adonuxt_test/.nuxt/server.js' in '/home/landan/www/adonuxt_test'
resolve '/home/landan/www/adonuxt_test/.nuxt/server.js' in '/home/landan/www/adonuxt_test'
  using description file: /home/landan/www/adonuxt_test/package.json (relative path: .)
  after using description file: /home/landan/www/adonuxt_test/package.json (relative path: .)
    using description file: /home/landan/www/adonuxt_test/package.json (relative path: ./.nuxt/server.js)
      as directory
        /home/landan/www/adonuxt_test/.nuxt/server.js doesn't exist
      no extension
        /home/landan/www/adonuxt_test/.nuxt/server.js doesn't exist
      .js
        /home/landan/www/adonuxt_test/.nuxt/server.js.js doesn't exist
      .json
        /home/landan/www/adonuxt_test/.nuxt/server.js.json doesn't exist
      .vue
        /home/landan/www/adonuxt_test/.nuxt/server.js.vue doesn't exist

/home/landan/www/adonuxt_test/node_modules/memory-fs/lib/MemoryFileSystem.js:114
                        throw new MemoryFileSystemError(errors.code.ENOENT, _path);
                        ^
Error: no such file or directory
    at MemoryFileSystem.readFileSync (/home/landan/www/adonuxt_test/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
    at Watching.handler (/home/landan/www/adonuxt_test/node_modules/nuxt/dist/nuxt.js:783:37)
    at Watching._done (/home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:94:7)
    at /home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:74:18
    at Compiler.emitRecords (/home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:351:37)
    at /home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:57:19
    at /home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:344:11
    at next (/home/landan/www/adonuxt_test/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/home/landan/www/adonuxt_test/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/landan/www/adonuxt_test/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:341:8)
    at Compiler.<anonymous> (/home/landan/www/adonuxt_test/node_modules/webpack/lib/Compiler.js:336:14)
    at /home/landan/www/adonuxt_test/node_modules/webpack/node_modules/async/dist/async.js:356:16
    at eachOfArrayLike (/home/landan/www/adonuxt_test/node_modules/webpack/node_modules/async/dist/async.js:929:9)
    at eachOf (/home/landan/www/adonuxt_test/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/home/landan/www/adonuxt_test/node_modules/webpack/node_modules/async/dist/async.js:3089:3)
[nodemon] app crashed - waiting for file changes before starting...
```

`throw new MemoryFileSystemError(errors.code.ENOENT, _path);`

I just looked inside the `.nuxt` folder and all of the files are gone.
Is there something I can change in config, to keep the files in `.nuxt` intact?

I think this may be due to webpack trying to rebuild files, while my functional tests are running

**Comment by Atinux** [comment]
What are doing your tests exactly @lmj0011 ?

**Comment by lmj0011** [comment]
>What are doing your tests exactly @lmj0011 ?

I'm running tests against an api lib

**api.js**
```js
const test = require('japa')
const Chance = require('chance')
const api = require('./api')

const chance = new Chance()

test.group('API', group => {
  group.beforeEach(() => {

  })

  test('it should log in a User', (assert) => {
    return api.login('user1', 'password1')
    .then(({ data }) => {
      assert.deepProperty(data, 'user')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should GET Instances', (assert) => {
    return api.getInstances()
    .then(({ data }) => {
      assert.deepProperty(data, 'instances')
      assert.isArray(data.instances, 'instances is a Collection')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should STORE an Instance', (assert) => {
    return api.createInstance({
      name: 'Instance' + chance.hash({length: 5}),
      server_id: chance.hash({length: 5}),
      env: {'APP_ENV': 'dev', 'APP_DEBUG': 'true'}
    })
    .then(({ data }) => {
      assert.deepProperty(data, 'instance')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should SHOW an Instance', (assert) => {
    return api.getInstance(1)
    .then(({ data }) => {
      assert.deepProperty(data, 'instance')
      assert.deepProperty(data, 'instance.id')
      assert.deepProperty(data, 'instance.name')
      assert.deepProperty(data, 'instance.status')
      assert.deepProperty(data, 'instance.server_id')
      assert.deepProperty(data, 'instance.env')
      assert.deepProperty(data, 'instance.created_at')
      assert.deepProperty(data, 'instance.updated_at')

      assert.isObject(data.instance, 'instance should be an Object')
      assert.isNumber(data.instance.id, 'instance.id should be a Number')
      assert.isString(data.instance.name, 'instance.name should be a String')
      assert.isString(data.instance.status, 'instance.status should be a String')
      assert.isString(data.instance.server_id, 'instance.server_id should be a String')
      assert.isObject(data.instance.env, 'instance.env should be an Object')
      assert.isString(data.instance.created_at, 'instance.created_at should be a String')
      assert.isString(data.instance.updated_at, 'instance.update_at should be a String')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should GET Users', (assert) => {
    return api.getUsers()
    .then(({ data }) => {
      assert.deepProperty(data, 'users')
      assert.isArray(data.users, 'instances is a Collection')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should STORE a User', (assert) => {
    return api.register({
      username: chance.first() + chance.hash({length: 5}),
      password: chance.hash({length: 5}),
      email: chance.email({domain: 'test.bid'})
    })
    .then(({ data }) => {
      assert.deepProperty(data, 'user')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })

  test('it should SHOW a User', (assert) => {
    return api.getUser(1)
    .then(({ data }) => {
      assert.deepProperty(data, 'user')
      assert.deepProperty(data, 'user.id')
      assert.deepProperty(data, 'user.username')
      assert.deepProperty(data, 'user.email')
      assert.deepProperty(data, 'user.password')
      assert.deepProperty(data, 'user.created_at')
      assert.deepProperty(data, 'user.updated_at')

      assert.isObject(data.user, 'user should be an Object')
      assert.isNumber(data.user.id, 'user.id should be a Number')
      assert.isString(data.user.username, 'user.username should be a String')
      assert.isString(data.user.email, 'user.email should be a String')
      assert.isString(data.user.password, 'user.password should be a String')
      assert.isString(data.user.created_at, 'user.created_at should be a String')
      assert.isString(data.user.updated_at, 'user.updated_at should be a String')
    })
    .catch(err => {
      assert.fail(err, null, err.message)
    })
  })
})

```

**Comment by Atinux** [comment]
You should not call : `npm run watch && node ./ace nuxtbuild && NODE_ENV=development node server.js`

It is `npm run dev` or `npm run build && npm start`

**Comment by lmj0011** [comment]
@Atinux 
Ok thanks, I ran the `npm run start` command before:

` node ./ace nuxtbuild && NODE_ENV=development node server.js`

but with the `NODE_ENV` changed to `development`, which calls the `this.nuxt.build()` inside the Controller's [constructor](https://github.com/nuxt/adonuxt/blob/master/app/Http/Controllers/NuxtController.js#L14). This was causing the app to rebuild after the one call to the Controller and crashing the tests.

I changed the env to disable CSRF Protection in my app, I suppose I will do it manually or use a different var for `NODE_ENV`
