### ISSUE TITLE
TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by lmj0011** [nuxt/adonuxt#26]
Getting this error on a specific page of my app.
Only happens when running in `dev` mode

What do it mean?

```sh
yarn dev v0.20.3
$ npm run watch && node ./ace nuxtbuild && node server.js  

> adonuxt_test@1.0.0 watch /home/landan/www/adonuxt-rp
> nodemon --watch app --watch bootstrap --watch config --watch .env

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/landan/www/adonuxt-rp/app/**/* /home/landan/www/adonuxt-rp/bootstrap/**/* /home/landan/www/adonuxt-rp/config/**/* .env
[nodemon] starting `node server.js`
info adonis:framework +0ms serving app on localhost:4000
webpack built 6c4e179a3673f9db62bf in 6127ms
client is authenticated!
webpack building...
webpack built 6c4e179a3673f9db62bf in 829ms
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /home/landan/www/adonuxt-rp/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Compilation.js:605:9)
    at Compilation.applyPluginsAsyncSeries (/home/landan/www/adonuxt-rp/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/home/landan/www/adonuxt-rp/node_modules/webpack/lib/Compilation.js:570:8)
    at /home/landan/www/adonuxt-rp/node_modules/webpack/lib/Compiler.js:474:16
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Atinux** [comment]
I just did a fresh install and it works fine now.

**Comment by lmj0011** [comment]
A fresh install of adonuxt?

**Comment by Atinux** [comment]
Yes try to redo the installation process of adonuxt.

Otherwise try to run ´yarn upgrade'

**Comment by lmj0011** [comment]
>Otherwise try to run ´yarn upgrade'

this did it for me, I'm now getting better error messages. Not sure which package(s) is responsible for that
