### ISSUE TITLE
this.nuxt.build is not a function

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/adonuxt#38]
Fresh new clone, cannot run any scripts. 

`TypeError: this.nuxt.build is not a function
    at new NuxtController (/AdonuxtTest/app/Http/Controllers/NuxtController.js:14:17)
    at Object.<anonymous> (/AdonuxtTest/app/Http/Controllers/NuxtController.js:24:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireStack (/AdonuxtTest/node_modules/require-stack/src/index.js:44:12)
    at Object.Ioc._autoLoad (/AdonuxtTest/node_modules/adonis-fold/src/Ioc/index.js:178:18)
    at Ioc.use (/AdonuxtTest/node_modules/adonis-fold/src/Ioc/index.js:378:18)
    at /AdonuxtTest/server.js:19:3
    at fold.Registrar.register.then (/AdonuxtTest/bootstrap/http.js:105:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
`

**Comment by JKChen** [comment]
I got the same error when i run "npm run serve:dev" after all dependencies installed.

**Comment by rachmanzz** [comment]
I got same problem

**Comment by jamesAtcodeninja** [comment]
Here's how I got it working 

`constructor () {
    const config = Config.get('nuxt');
    this.nuxt = new Nuxt(config);
    this.nuxt.then((nuxt) => {
      this.nuxt = nuxt;
      if (config.dev) {
        this.nuxt.build();
      }
    });
  }`

**Comment by lmj0011** [comment]
@jamesAtcodeninja 

even though the error shows the location, it still would have been nice to include a link to where you made that change, for the sake of verbosity.

https://github.com/nuxt/adonuxt/blob/master/app/Http/Controllers/NuxtController.js#L9-L16

**Comment by kireerik** [comment]
This is still an issue or maybe a regression.
`(node:9644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Nuxt is not a constructor`
