### ISSUE TITLE
TypeError: (intermediate value).then is not a function

### ISSUE THREAD

**Issue by jzucadi** [nuxt/adonuxt#43]
Not sure if I am the only one. I followed the installation instructions for the adonis cli and the project gets set up, but when I run "npm run dev" I receive an error which reads:

`TypeError: (intermediate value).then is not a function
    at new NuxtController (/Users/~/app/Http/Controllers/NuxtController.js:13:8)
    at Object.<anonymous> (/Users/~/app/Http/Controllers/NuxtController.js:26:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireStack (/Users/~/node_modules/require-stack/src/index.js:44:12)
    at Object.Ioc._autoLoad (/Users/~node_modules/adonis-fold/src/Ioc/index.js:178:18)
    at Ioc.use (/Users/~/node_modules/adonis-fold/src/Ioc/index.js:378:18)
    at /Users/~/server.js:19:3
    at fold.Registrar.register.then (/Users/~/bootstrap/http.js:105:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)`

There is also en error with the logo: 
`Module parse failed: /Users/~/resources/assets/img/logo.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.`

Any ideas?

**Comment by motia** [comment]
The error is caused by an api change of nuxt. Look at this commit, to fix it
https://github.com/motia/adonuxt/commit/ecd5707794d56b3b7c7205c33a0593f71309535d

**Comment by jzucadi** [comment]
thank you
